from pathlib import Path
from posixpath import join

def readFile(filename, subdir = None, Path=Path):
    if subdir is None:
        return open(Path(__file__).with_name(filename), encoding='UTF-8').read()
    else:
        return open(Path(__file__).parent.joinpath(subdir, filename), encoding='UTF-8').read()

def writeFile(filename, text, Path=Path):
    open(Path(__file__).with_name(filename), encoding='UTF-8', mode='w').write(text)

individual_courses_text = readFile('individual_courses.txt')
groupe_courses_text = readFile('group_courses.txt')
letniy_intensiv_text = readFile('letniy_intensiv.txt')
letniy_intensiv_2_text = readFile('letniy_intensiv_2.txt')
komu_podhodit_text = readFile('komu_podhodit.txt')
temy_int = readFile('temy_int.txt')
bibla_text = readFile('bibla.txt')
gista_course_txt = readFile('gista_course.txt')
for_who_txt = readFile('for_who.txt')
tarifs_course_txt = readFile('tarifs_course.txt')
conspects_course_txt = readFile('conspeccts_course.txt')
how_learn_txt = readFile('how_learn.txt')
courator_txt = readFile('courator.txt')
why_us_txt = readFile('why_us.txt')
mission_txt = readFile('mission.txt')
himiya_courses_txt = readFile('himiya_courses.txt')
for_who_is_txt = readFile('for_who_is.txt')
checklist_txt = readFile('checklist.txt')
cnsint_txt = readFile('cnsint.txt')
not_sub_txt = readFile('not_sub.txt')
sersod_txt = readFile('SerSod.txt')
anatrepit_txt = readFile('repitAnat.txt')
anatint_txt = readFile('AnatInt.txt')
vskint_txt = readFile('vskint.txt')
embriogenez_txt = readFile('Embriogenez.txt')
remember5_txt = readFile('remember5.txt')
remember1_txt = readFile('remember1.txt')
gista_ekz_txt = readFile('gist_ekz.txt')
anat_ekz_txt = readFile('anat_ekz.txt')
zadachi_txt = readFile('zadachi.txt')
okraski_txt = readFile('okraski.txt')
nervnaya_sys_txt = readFile('nervnaya_sys.txt')
okraski_conspect_txt = readFile('okraski_conspect.txt')
rotpol_txt = readFile('rot_pol.txt')
org_chuv_txt = readFile('org_chuv.txt')
klet_poverh_txt = readFile('klet_poverh.txt')
remember5_1_txt = readFile('remember5.1.txt')
epiteliy_txt = readFile('epiteliy.txt')
pishevar1_txt = readFile('pishevar1.txt')
remember1_1_txt = readFile('remember1.1.txt')
web_obsh_gist_txt = readFile('web_obsh_gist.txt')
web_hrash_txt = readFile('web_hrash.txt')
web_kosty_txt = readFile('web_kosty.txt')
remember6_txt = readFile('remember6.txt')
remember2_txt = readFile('remember2.txt')
web_nervy_txt = readFile('web_nervy.txt')
remember3_txt = readFile('remember3.txt')
remember7_txt = readFile('remember7.txt')
intensiv_cns_txt = readFile('intensiv_cns.txt')
time_guide_txt = readFile('time_guide.txt')
guide_in_txt = readFile('guide_in.txt')
guide_chapters_txt = readFile('guide_chapters.txt')
guide_who_txt = readFile('guide_who.txt')
low_price_txt = readFile('low_price.txt')

guide_v2_start_txt = readFile('start.txt', subdir='guide_v2')
guide_v2_intro_txt = readFile('intro.txt', subdir='guide_v2')
guide_v2_fasttrack_txt = readFile('fasttrack.txt', subdir='guide_v2')
guide_v2_whats_inside_txt = readFile('whats_inside.txt', subdir='guide_v2')
guide_v2_contents_txt = readFile('contents.txt', subdir='guide_v2')
guide_v2_example_page_txt = readFile('example_page.txt', subdir='guide_v2')
guide_v2_target_audience_txt = readFile('target_audience.txt', subdir='guide_v2')
guide_v2_reviews_txt = readFile('reviews.txt', subdir='guide_v2')
guide_v2_questionnaire_txt = readFile('questionnaire.txt', subdir='guide_v2')
guide_v2_subscribe_after_buy_txt = readFile('subscribe_after_buy.txt', subdir='guide_v2')


ai_for_med_2000_txt = readFile('ai_for_med_2000.txt')
ai_for_med_3000_txt = readFile('ai_for_med_3000.txt')
oferta_txt = readFile('oferta.txt')